project:
  type: website

website:
  title: "VAA-GroupProj"
  image: "images/shoal.png"
  favicon: "images/fishbone-icon.png"
  navbar:
    logo: "images/shoal.png"
    title: false
    collapse-below: lg
    search: true
    right:
      - text: "Home"
        menu: 
          - text: "Home"
            href: index.qmd
          - text: "About the Team"
            href: about.html
          - text: "testing"
            href: testing.html
            
format:
  html:
    toc: true
    theme: 
      - journal
      - theme.scss
    highlight-style: tango
    code-copy: hover
    code-overflow: wrap
    css: styles.css

editor: visual

