project:
  type: website

website:
  title: "FindingNEMO"
  image: "images/shoal.png"
  favicon: "images/fishbone-icon.png"
  navbar:
    logo: "images/shoal.png"
    title: false
    collapse-below: lg
    search: true
    right:
      - text: "The Team"
        href: about.html
      - text: "Proposal"
        href: proposal/proposal.html
      - text: "Fishy Business"
        href: mc3_1/fishy_business.html
      - text: "Fishy Similarities"
        href: mc3_2/fishy_similarities.html
      - text: "Shiny App"
        menu:
          - text: "Anomalous Structures"
            href: about.html
          - text: "Similarities"
            href: about.html
            
format:
  html:
    grid:
      margin-width: 150px
    toc: true
    theme: 
      - theme.scss
    highlight-style: tango
    code-copy: hover
    code-overflow: wrap
    css: styles.css

editor: visual

